@extends('layouts.navbars')
@section('title','Detalle de actividad')
@section('content')
@php
$urlMedio=function($url){ if(!$url) return ''; if(\Illuminate\Support\Str::startsWith($url,['http://','https://'])) return $url; $ruta=ltrim($url,'/'); return asset(\Illuminate\Support\Str::startsWith($ruta,'storage/')?$ruta:'storage/'.$ruta); };
$portada=$actividad->medios->whereNull('id_item_actividad')->whereNull('id_sesion')->firstWhere('es_portada',true);
@endphp
<div class="mx-auto w-full max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
<div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
<div class="min-w-0"><a href="{{ route('admin.actividades.index') }}" class="mb-2 inline-flex text-sm text-gray-400 hover:text-white">← Volver a actividades</a><div class="flex flex-wrap items-center gap-3"><h1 class="truncate text-2xl font-semibold text-white">{{ $actividad->nombre }}</h1><span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-gray-300">{{ str_replace('_',' ',ucfirst($actividad->estado_publicacion)) }}</span></div><p class="mt-2 max-w-3xl text-sm text-gray-400">{{ $actividad->resumen ?: 'Sin resumen.' }}</p></div>
<div class="flex flex-wrap gap-2">@if(in_array($actividad->estado_publicacion,['borrador','cambios_solicitados'],true))<a href="{{ route('admin.actividades.edit',$actividad) }}" class="inline-flex items-center justify-center rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-medium text-white hover:bg-white/10">Editar datos generales</a><a href="{{ route('admin.actividades.configurar',$actividad) }}" class="inline-flex items-center justify-center rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-black hover:bg-emerald-400">Configurar actividad</a>@endif</div>
</div>
<div class="grid grid-cols-1 gap-6 xl:grid-cols-[1.35fr_.65fr]">
<div class="space-y-6">
<section class="overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]">@if($portada)<img src="{{ $urlMedio($portada->url) }}" alt="{{ $portada->texto_alternativo ?: $actividad->nombre }}" class="aspect-[16/7] w-full object-cover">@endif<div class="p-5 sm:p-6"><h2 class="text-base font-semibold text-white">Información general</h2><div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">
<div><p class="text-xs uppercase tracking-wide text-gray-500">Categoría</p><p class="mt-1 text-sm text-gray-200">{{ $actividad->categoria?->nombre ?: 'Sin categoría' }}</p></div><div><p class="text-xs uppercase tracking-wide text-gray-500">Visibilidad</p><p class="mt-1 text-sm text-gray-200">{{ ucfirst($actividad->visibilidad) }}</p></div>
<div><p class="text-xs uppercase tracking-wide text-gray-500">Visible desde</p><p class="mt-1 text-sm text-gray-200">{{ $actividad->visible_desde?->format('d/m/Y H:i') ?: 'Sin definir' }}</p></div><div><p class="text-xs uppercase tracking-wide text-gray-500">Visible hasta</p><p class="mt-1 text-sm text-gray-200">{{ $actividad->visible_hasta?->format('d/m/Y H:i') ?: 'Sin definir' }}</p></div>
<div><p class="text-xs uppercase tracking-wide text-gray-500">Realización desde</p><p class="mt-1 text-sm text-gray-200">{{ $actividad->realizacion_desde?->format('d/m/Y H:i') ?: 'Sin definir' }}</p></div><div><p class="text-xs uppercase tracking-wide text-gray-500">Realización hasta</p><p class="mt-1 text-sm text-gray-200">{{ $actividad->realizacion_hasta?->format('d/m/Y H:i') ?: 'Sin definir' }}</p></div>
</div>@if($actividad->descripcion)<div class="mt-6 border-t border-white/10 pt-5"><p class="whitespace-pre-line text-sm leading-6 text-gray-300">{{ $actividad->descripcion }}</p></div>@endif</div></section>
<section class="rounded-2xl border border-white/10 bg-white/[.03] p-5 sm:p-6"><div class="flex items-center justify-between gap-3"><h2 class="text-base font-semibold text-white">Programación</h2><span class="text-xs text-gray-500">{{ $actividad->sesiones->count() }} sesión(es)</span></div>
@forelse($actividad->sesiones->sortBy('orden') as $sesion)<div class="mt-4 rounded-xl border border-white/10 bg-black/10 p-4"><div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-medium text-gray-200">{{ $sesion->nombre }}</p><p class="mt-1 text-xs text-gray-500">{{ $sesion->fecha_inicio?->format('d/m/Y H:i') }}@if($sesion->fecha_fin) — {{ $sesion->fecha_fin->format('d/m/Y H:i') }}@endif</p></div>@if($sesion->cupo)<span class="text-xs text-gray-400">Cupo: {{ $sesion->cupo }}</span>@endif</div>@if($sesion->ubicacion)<p class="mt-3 text-sm text-gray-400">{{ $sesion->ubicacion }}</p>@endif</div>@empty<p class="mt-4 text-sm text-gray-500">No hay sesiones configuradas.</p>@endforelse
</section></div>
<aside class="space-y-6"><section class="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 class="text-sm font-semibold text-white">Clasificación</h2><div class="mt-4 flex flex-wrap gap-2">@forelse($actividad->etiquetas as $etiqueta)<span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-gray-300">{{ $etiqueta->nombre }}</span>@empty<span class="text-sm text-gray-500">Sin etiquetas</span>@endforelse</div></section>
<section class="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 class="text-sm font-semibold text-white">Inscripciones</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-gray-500">Habilitadas</dt><dd class="text-gray-200">{{ $actividad->habilita_inscripcion?'Sí':'No' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500">Cupo total</dt><dd class="text-gray-200">{{ $actividad->cupo_total ?? 'Sin límite' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500">Requiere cuenta</dt><dd class="text-gray-200">{{ $actividad->requiere_cuenta?'Sí':'No' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500">Lista de espera</dt><dd class="text-gray-200">{{ $actividad->permite_lista_espera?'Sí':'No' }}</dd></div></dl></section></aside>
</div></div>
@endsection
